# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Integration Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:14-buster-slim
    services:
      emurator:
        image: banban525/echonet-lite-kaden-emulator:latest
      mqttserver:
        image: eclipse-mosquitto
    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - run: npm run test:integration
      env:
        mqttserver: mqtt://mqttserver
        emurator: http://emurator:3000
