# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:14-buster-slim
    environment:
      mqttserver: mqtt://mqttserver
      emurator: http://emurator:3000
    services:
      emurator:
        image: banban525/echonet-lite-kaden-emulator:latest
      mqttserver:
        image: eclipse-mosquitto:2.0.15
    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - run: npm run test:integration
